#! -*- mode: sh; sh-shell: bash -*-

git pull
cp copy-button.js ../assets/js/
cp copy-button.css ../assets/css/
cp _config.yml ../
echo dummy >> ../dummy
git add ..
git commit -m 'automatic commit'
git push
